stages:
  - name: File Operations
    steps:
      - name: Rename README File
        action: FileRenameAction
        options:
          srcPath: "./README_old.md"
          targetPath: "./README.md"
