# pack.yml

stages:

  - name: CleanBuildDirectory
    description: "Clean the build directory before starting a new build."
    steps:
      - name: CleanBuildDirStep
        action: DirectoryCleanAction
        options:
          dirPath: "./dist"  # Path to the directory to be cleaned

globalOptions:
  verboseLogging: true


# Global options applicable to the entire pipeline
# globalOptions:
#   logLevel: info           # Log level for the pipeline (verbose, info, warn, error)
#   stepTimeout: 30000       # Timeout for each step in milliseconds